ALTER TABLE users ADD COLUMN cpf VARCHAR(14) UNIQUE;
ALTER TABLE users ADD COLUMN phone VARCHAR(20);
ALTER TABLE users ALTER COLUMN password DROP NOT NULL;

---- create above / drop below ----

ALTER TABLE users DROP COLUMN IF EXISTS cpf;
ALTER TABLE users DROP COLUMN IF EXISTS phone;
ALTER TABLE users ALTER COLUMN password SET NOT NULL;
