// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: investment.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInvestment = `-- name: DeleteInvestment :exec
DELETE FROM investments WHERE id = $1 AND user_id = $2
`

type DeleteInvestmentParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteInvestment(ctx context.Context, arg DeleteInvestmentParams) error {
	_, err := q.db.Exec(ctx, deleteInvestment, arg.ID, arg.UserID)
	return err
}

const getInvestmentByID = `-- name: GetInvestmentByID :one
SELECT
    i.id,
    i.user_id,
    i.amount,
    i.description,
    i.invested_at,
    i.created_at,
    i.movement_type,
    it.slug AS type_slug,
    it.name AS type_name
FROM investments i
JOIN investment_types it ON i.investment_type_id = it.id
WHERE i.id = $1 AND i.user_id = $2
`

type GetInvestmentByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetInvestmentByIDRow struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	Amount       int64              `json:"amount"`
	Description  pgtype.Text        `json:"description"`
	InvestedAt   pgtype.Timestamptz `json:"invested_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	MovementType string             `json:"movement_type"`
	TypeSlug     string             `json:"type_slug"`
	TypeName     string             `json:"type_name"`
}

func (q *Queries) GetInvestmentByID(ctx context.Context, arg GetInvestmentByIDParams) (GetInvestmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getInvestmentByID, arg.ID, arg.UserID)
	var i GetInvestmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.InvestedAt,
		&i.CreatedAt,
		&i.MovementType,
		&i.TypeSlug,
		&i.TypeName,
	)
	return i, err
}

const getInvestmentSummaryByPeriod = `-- name: GetInvestmentSummaryByPeriod :many
SELECT
    it.slug AS type_slug,
    it.name AS type_name,
    SUM(CASE WHEN i.movement_type = 'withdrawal' THEN -i.amount ELSE i.amount END) AS total
FROM investments i
JOIN investment_types it ON i.investment_type_id = it.id
WHERE i.user_id = $1
  AND i.invested_at >= $2
  AND i.invested_at < $3
GROUP BY it.id, it.slug, it.name
ORDER BY total DESC
`

type GetInvestmentSummaryByPeriodParams struct {
	UserID       int64              `json:"user_id"`
	InvestedAt   pgtype.Timestamptz `json:"invested_at"`
	InvestedAt_2 pgtype.Timestamptz `json:"invested_at_2"`
}

type GetInvestmentSummaryByPeriodRow struct {
	TypeSlug string `json:"type_slug"`
	TypeName string `json:"type_name"`
	Total    int64  `json:"total"`
}

func (q *Queries) GetInvestmentSummaryByPeriod(ctx context.Context, arg GetInvestmentSummaryByPeriodParams) ([]GetInvestmentSummaryByPeriodRow, error) {
	rows, err := q.db.Query(ctx, getInvestmentSummaryByPeriod, arg.UserID, arg.InvestedAt, arg.InvestedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInvestmentSummaryByPeriodRow
	for rows.Next() {
		var i GetInvestmentSummaryByPeriodRow
		if err := rows.Scan(&i.TypeSlug, &i.TypeName, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvestmentTypeBySlug = `-- name: GetInvestmentTypeBySlug :one
SELECT id, slug, name, description, created_at FROM investment_types WHERE slug = $1
`

func (q *Queries) GetInvestmentTypeBySlug(ctx context.Context, slug string) (InvestmentType, error) {
	row := q.db.QueryRow(ctx, getInvestmentTypeBySlug, slug)
	var i InvestmentType
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalInvestmentsByUser = `-- name: GetTotalInvestmentsByUser :one
SELECT COALESCE(SUM(
    CASE WHEN movement_type = 'withdrawal' THEN -amount ELSE amount END
), 0)::BIGINT AS total
FROM investments
WHERE user_id = $1
`

func (q *Queries) GetTotalInvestmentsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalInvestmentsByUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const insertInvestment = `-- name: InsertInvestment :one
INSERT INTO investments (user_id, investment_type_id, amount, description, invested_at, movement_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, investment_type_id, amount, description, invested_at, created_at, movement_type
`

type InsertInvestmentParams struct {
	UserID           int64              `json:"user_id"`
	InvestmentTypeID int32              `json:"investment_type_id"`
	Amount           int64              `json:"amount"`
	Description      pgtype.Text        `json:"description"`
	InvestedAt       pgtype.Timestamptz `json:"invested_at"`
	MovementType     string             `json:"movement_type"`
}

func (q *Queries) InsertInvestment(ctx context.Context, arg InsertInvestmentParams) (Investment, error) {
	row := q.db.QueryRow(ctx, insertInvestment,
		arg.UserID,
		arg.InvestmentTypeID,
		arg.Amount,
		arg.Description,
		arg.InvestedAt,
		arg.MovementType,
	)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvestmentTypeID,
		&i.Amount,
		&i.Description,
		&i.InvestedAt,
		&i.CreatedAt,
		&i.MovementType,
	)
	return i, err
}

const listInvestmentTypes = `-- name: ListInvestmentTypes :many
SELECT id, slug, name, description, created_at FROM investment_types ORDER BY name
`

func (q *Queries) ListInvestmentTypes(ctx context.Context) ([]InvestmentType, error) {
	rows, err := q.db.Query(ctx, listInvestmentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvestmentType
	for rows.Next() {
		var i InvestmentType
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentsByUser = `-- name: ListInvestmentsByUser :many
SELECT
    i.id,
    i.user_id,
    i.amount,
    i.description,
    i.invested_at,
    i.created_at,
    i.movement_type,
    it.slug AS type_slug,
    it.name AS type_name
FROM investments i
JOIN investment_types it ON i.investment_type_id = it.id
WHERE i.user_id = $1
ORDER BY i.invested_at DESC
`

type ListInvestmentsByUserRow struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	Amount       int64              `json:"amount"`
	Description  pgtype.Text        `json:"description"`
	InvestedAt   pgtype.Timestamptz `json:"invested_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	MovementType string             `json:"movement_type"`
	TypeSlug     string             `json:"type_slug"`
	TypeName     string             `json:"type_name"`
}

func (q *Queries) ListInvestmentsByUser(ctx context.Context, userID int64) ([]ListInvestmentsByUserRow, error) {
	rows, err := q.db.Query(ctx, listInvestmentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvestmentsByUserRow
	for rows.Next() {
		var i ListInvestmentsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Description,
			&i.InvestedAt,
			&i.CreatedAt,
			&i.MovementType,
			&i.TypeSlug,
			&i.TypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentsByUserAndPeriod = `-- name: ListInvestmentsByUserAndPeriod :many
SELECT
    i.id,
    i.user_id,
    i.amount,
    i.description,
    i.invested_at,
    i.created_at,
    i.movement_type,
    it.slug AS type_slug,
    it.name AS type_name
FROM investments i
JOIN investment_types it ON i.investment_type_id = it.id
WHERE i.user_id = $1
  AND i.invested_at >= $2
  AND i.invested_at < $3
ORDER BY i.invested_at DESC
`

type ListInvestmentsByUserAndPeriodParams struct {
	UserID       int64              `json:"user_id"`
	InvestedAt   pgtype.Timestamptz `json:"invested_at"`
	InvestedAt_2 pgtype.Timestamptz `json:"invested_at_2"`
}

type ListInvestmentsByUserAndPeriodRow struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	Amount       int64              `json:"amount"`
	Description  pgtype.Text        `json:"description"`
	InvestedAt   pgtype.Timestamptz `json:"invested_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	MovementType string             `json:"movement_type"`
	TypeSlug     string             `json:"type_slug"`
	TypeName     string             `json:"type_name"`
}

func (q *Queries) ListInvestmentsByUserAndPeriod(ctx context.Context, arg ListInvestmentsByUserAndPeriodParams) ([]ListInvestmentsByUserAndPeriodRow, error) {
	rows, err := q.db.Query(ctx, listInvestmentsByUserAndPeriod, arg.UserID, arg.InvestedAt, arg.InvestedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvestmentsByUserAndPeriodRow
	for rows.Next() {
		var i ListInvestmentsByUserAndPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Description,
			&i.InvestedAt,
			&i.CreatedAt,
			&i.MovementType,
			&i.TypeSlug,
			&i.TypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
