// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: postgres.sql

package pgstore

import (
	"context"
)

const getDBStatus = `-- name: GetDBStatus :one
SELECT
    split_part(current_setting('server_version'), ' ', 1) AS version,
    current_setting('max_connections')::int AS max_connections,
    (SELECT version FROM schema_version ORDER BY version DESC LIMIT 1) AS last_migration
FROM (SELECT 1) AS dummy
`

type GetDBStatusRow struct {
	Version        string `json:"version"`
	MaxConnections int32  `json:"max_connections"`
	LastMigration  int32  `json:"last_migration"`
}

func (q *Queries) GetDBStatus(ctx context.Context) (GetDBStatusRow, error) {
	row := q.db.QueryRow(ctx, getDBStatus)
	var i GetDBStatusRow
	err := row.Scan(&i.Version, &i.MaxConnections, &i.LastMigration)
	return i, err
}
