// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revenue.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRevenueSummaryByPeriod = `-- name: GetRevenueSummaryByPeriod :one
SELECT COALESCE(SUM(amount), 0)::BIGINT AS total
FROM revenues
WHERE user_id = $1
  AND received_at >= $2
  AND received_at < $3
`

type GetRevenueSummaryByPeriodParams struct {
	UserID       int64              `json:"user_id"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	ReceivedAt_2 pgtype.Timestamptz `json:"received_at_2"`
}

func (q *Queries) GetRevenueSummaryByPeriod(ctx context.Context, arg GetRevenueSummaryByPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRevenueSummaryByPeriod, arg.UserID, arg.ReceivedAt, arg.ReceivedAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const insertRevenue = `-- name: InsertRevenue :one
INSERT INTO revenues (user_id, amount, description, received_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, amount, description, received_at, created_at
`

type InsertRevenueParams struct {
	UserID      int64              `json:"user_id"`
	Amount      int64              `json:"amount"`
	Description pgtype.Text        `json:"description"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
}

func (q *Queries) InsertRevenue(ctx context.Context, arg InsertRevenueParams) (Revenue, error) {
	row := q.db.QueryRow(ctx, insertRevenue,
		arg.UserID,
		arg.Amount,
		arg.Description,
		arg.ReceivedAt,
	)
	var i Revenue
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listRevenuesByUser = `-- name: ListRevenuesByUser :many
SELECT id, user_id, amount, description, received_at, created_at
FROM revenues
WHERE user_id = $1
ORDER BY received_at DESC
`

func (q *Queries) ListRevenuesByUser(ctx context.Context, userID int64) ([]Revenue, error) {
	rows, err := q.db.Query(ctx, listRevenuesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Revenue
	for rows.Next() {
		var i Revenue
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Description,
			&i.ReceivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
