// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telegram_conversation.sql

package pgstore

import (
	"context"
)

const deleteConversationState = `-- name: DeleteConversationState :exec
DELETE FROM telegram_conversations WHERE chat_id = $1
`

func (q *Queries) DeleteConversationState(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, deleteConversationState, chatID)
	return err
}

const getConversationState = `-- name: GetConversationState :one
SELECT chat_id, step, data, updated_at
FROM telegram_conversations
WHERE chat_id = $1
`

func (q *Queries) GetConversationState(ctx context.Context, chatID int64) (TelegramConversation, error) {
	row := q.db.QueryRow(ctx, getConversationState, chatID)
	var i TelegramConversation
	err := row.Scan(
		&i.ChatID,
		&i.Step,
		&i.Data,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConversationState = `-- name: UpsertConversationState :exec
INSERT INTO telegram_conversations (chat_id, step, data, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (chat_id) DO UPDATE
SET step = EXCLUDED.step,
    data = EXCLUDED.data,
    updated_at = NOW()
`

type UpsertConversationStateParams struct {
	ChatID int64  `json:"chat_id"`
	Step   string `json:"step"`
	Data   string `json:"data"`
}

func (q *Queries) UpsertConversationState(ctx context.Context, arg UpsertConversationStateParams) error {
	_, err := q.db.Exec(ctx, upsertConversationState, arg.ChatID, arg.Step, arg.Data)
	return err
}
