services:
  postgres:
    image: postgres:16-alpine
    container_name: fintech_kodify_db
    environment:
      POSTGRES_USER: kodify
      POSTGRES_PASSWORD: kodify
      POSTGRES_DB: fintech_kodify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kodify -d fintech_kodify"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
