// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expense.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses WHERE id = $1 AND user_id = $2
`

type DeleteExpenseParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error {
	_, err := q.db.Exec(ctx, deleteExpense, arg.ID, arg.UserID)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT
    e.id,
    e.user_id,
    e.amount,
    e.description,
    e.occurred_at,
    e.created_at,
    ec.slug AS category_slug,
    ec.name AS category_name
FROM expenses e
LEFT JOIN expense_categories ec ON e.category_id = ec.id
WHERE e.id = $1 AND e.user_id = $2
`

type GetExpenseByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetExpenseByIDRow struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	Amount       int64              `json:"amount"`
	Description  pgtype.Text        `json:"description"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CategorySlug pgtype.Text        `json:"category_slug"`
	CategoryName pgtype.Text        `json:"category_name"`
}

func (q *Queries) GetExpenseByID(ctx context.Context, arg GetExpenseByIDParams) (GetExpenseByIDRow, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, arg.ID, arg.UserID)
	var i GetExpenseByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.CategorySlug,
		&i.CategoryName,
	)
	return i, err
}

const getExpenseCategoryBySlug = `-- name: GetExpenseCategoryBySlug :one
SELECT id, slug, name, description, created_at FROM expense_categories WHERE slug = $1
`

func (q *Queries) GetExpenseCategoryBySlug(ctx context.Context, slug string) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, getExpenseCategoryBySlug, slug)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const insertExpense = `-- name: InsertExpense :one
INSERT INTO expenses (user_id, category_id, amount, description, occurred_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, category_id, amount, description, occurred_at, created_at
`

type InsertExpenseParams struct {
	UserID      int64              `json:"user_id"`
	CategoryID  pgtype.Int4        `json:"category_id"`
	Amount      int64              `json:"amount"`
	Description pgtype.Text        `json:"description"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertExpense(ctx context.Context, arg InsertExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, insertExpense,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.OccurredAt,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExpenseCategories = `-- name: ListExpenseCategories :many
SELECT id, slug, name, description, created_at FROM expense_categories ORDER BY name
`

func (q *Queries) ListExpenseCategories(ctx context.Context) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, listExpenseCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseCategory
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByUser = `-- name: ListExpensesByUser :many
SELECT
    e.id,
    e.user_id,
    e.amount,
    e.description,
    e.occurred_at,
    e.created_at,
    ec.slug AS category_slug,
    ec.name AS category_name
FROM expenses e
LEFT JOIN expense_categories ec ON e.category_id = ec.id
WHERE e.user_id = $1
ORDER BY e.occurred_at DESC
`

type ListExpensesByUserRow struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	Amount       int64              `json:"amount"`
	Description  pgtype.Text        `json:"description"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CategorySlug pgtype.Text        `json:"category_slug"`
	CategoryName pgtype.Text        `json:"category_name"`
}

func (q *Queries) ListExpensesByUser(ctx context.Context, userID int64) ([]ListExpensesByUserRow, error) {
	rows, err := q.db.Query(ctx, listExpensesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesByUserRow
	for rows.Next() {
		var i ListExpensesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Description,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.CategorySlug,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByUserAndPeriod = `-- name: ListExpensesByUserAndPeriod :many
SELECT
    e.id,
    e.user_id,
    e.amount,
    e.description,
    e.occurred_at,
    e.created_at,
    ec.slug AS category_slug,
    ec.name AS category_name
FROM expenses e
LEFT JOIN expense_categories ec ON e.category_id = ec.id
WHERE e.user_id = $1
  AND e.occurred_at >= $2
  AND e.occurred_at < $3
ORDER BY e.occurred_at DESC
`

type ListExpensesByUserAndPeriodParams struct {
	UserID       int64              `json:"user_id"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
}

type ListExpensesByUserAndPeriodRow struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	Amount       int64              `json:"amount"`
	Description  pgtype.Text        `json:"description"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CategorySlug pgtype.Text        `json:"category_slug"`
	CategoryName pgtype.Text        `json:"category_name"`
}

func (q *Queries) ListExpensesByUserAndPeriod(ctx context.Context, arg ListExpensesByUserAndPeriodParams) ([]ListExpensesByUserAndPeriodRow, error) {
	rows, err := q.db.Query(ctx, listExpensesByUserAndPeriod, arg.UserID, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesByUserAndPeriodRow
	for rows.Next() {
		var i ListExpensesByUserAndPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Description,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.CategorySlug,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
