// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link_token.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getValidLinkToken = `-- name: GetValidLinkToken :one
SELECT id, user_id, token, expires_at, used_at, created_at FROM telegram_link_tokens
WHERE token = $1
  AND expires_at > NOW()
  AND used_at IS NULL
`

func (q *Queries) GetValidLinkToken(ctx context.Context, token string) (TelegramLinkToken, error) {
	row := q.db.QueryRow(ctx, getValidLinkToken, token)
	var i TelegramLinkToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertLinkToken = `-- name: InsertLinkToken :one
INSERT INTO telegram_link_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertLinkTokenParams struct {
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertLinkToken(ctx context.Context, arg InsertLinkTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertLinkToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markLinkTokenUsed = `-- name: MarkLinkTokenUsed :exec
UPDATE telegram_link_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkLinkTokenUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markLinkTokenUsed, id)
	return err
}
