// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Expense struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	CategoryID  pgtype.Int4        `json:"category_id"`
	Amount      int64              `json:"amount"`
	Description pgtype.Text        `json:"description"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ExpenseCategory struct {
	ID          int32              `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Investment struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	InvestmentTypeID int32              `json:"investment_type_id"`
	Amount           int64              `json:"amount"`
	Description      pgtype.Text        `json:"description"`
	InvestedAt       pgtype.Timestamptz `json:"invested_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type InvestmentType struct {
	ID          int32              `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type User struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	Password       string             `json:"password"`
	TelegramChatID pgtype.Int8        `json:"telegram_chat_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	RoleID         pgtype.Int8        `json:"role_id"`
}
