// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, created_at FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, telegram_chat_id, created_at, updated_at, role_id FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.TelegramChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password, telegram_chat_id, created_at, updated_at, role_id FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.TelegramChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
	)
	return i, err
}

const getUserByTelegramChatID = `-- name: GetUserByTelegramChatID :one
SELECT id, name, email, password, telegram_chat_id, created_at, updated_at, role_id FROM users
WHERE telegram_chat_id = $1
`

func (q *Queries) GetUserByTelegramChatID(ctx context.Context, telegramChatID pgtype.Int8) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramChatID, telegramChatID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.TelegramChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT p.name
FROM users u
JOIN roles r ON u.role_id = r.id
JOIN role_permissions rp ON r.id = rp.role_id
JOIN permissions p ON rp.permission_id = p.id
WHERE u.email = $1
`

func (q *Queries) GetUserPermissions(ctx context.Context, email string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithRole = `-- name: GetUserWithRole :one
SELECT
    u.id,
    u.name,
    u.email,
    u.password,
    u.telegram_chat_id,
    u.role_id,
    r.name AS role_name
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.email = $1
`

type GetUserWithRoleRow struct {
	ID             int64       `json:"id"`
	Name           string      `json:"name"`
	Email          string      `json:"email"`
	Password       string      `json:"password"`
	TelegramChatID pgtype.Int8 `json:"telegram_chat_id"`
	RoleID         pgtype.Int8 `json:"role_id"`
	RoleName       pgtype.Text `json:"role_name"`
}

func (q *Queries) GetUserWithRole(ctx context.Context, email string) (GetUserWithRoleRow, error) {
	row := q.db.QueryRow(ctx, getUserWithRole, email)
	var i GetUserWithRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.TelegramChatID,
		&i.RoleID,
		&i.RoleName,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (name, email, password)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertUserParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Name, arg.Email, arg.Password)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateUserTelegramChatID = `-- name: UpdateUserTelegramChatID :exec
UPDATE users
SET telegram_chat_id = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserTelegramChatIDParams struct {
	ID             int64       `json:"id"`
	TelegramChatID pgtype.Int8 `json:"telegram_chat_id"`
}

func (q *Queries) UpdateUserTelegramChatID(ctx context.Context, arg UpdateUserTelegramChatIDParams) error {
	_, err := q.db.Exec(ctx, updateUserTelegramChatID, arg.ID, arg.TelegramChatID)
	return err
}
